[package]
name = "flow-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
flow-types = { path = "../flow-types" }
k8s-openapi = { workspace = true, features = ["v1_29"] }
kube = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde_yaml = "0.9"
futures = "0.3"
